package com.Bedirhan.FourthDayOfTheChallenge.Homeworks.ExceptionHandling;

public class TryCatchDemo {
    public static void main(String[] args) {
//        int a =19;
//        int b = 0;
//        int c;
//        try{
//            c = a/b;
//        }
//        catch (ArithmeticException e){  // exception türü
//            System.out.println("hata: "+e.toString());
//        }




    }


}
